name: 'aws-cdk-action'
author: 'Scott Brenner <scott@scottbrenner.me>'
description: 'GitHub Action for AWS CDK'
runs:
  pre: 'dockersetup.sh'
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'box'
  color: 'yellow'
